apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - gateway-class.yaml
  - dashboard-route.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 39.0.2 # renovate: github-releases=traefik/traefik
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
    includeCRDs: true
